### ISSUE TITLE
App not launching after windows shutdown and restart.

### ISSUE THREAD

**Issue by pdxpilot** [astenlund/fs2ff#13] opened 2020-10-18 21:18 UTC
So it worked yesterday as I thought it was a network issue and I uninstalled and reinstalled fs2ff. Today I attempted to launch fs2ff and the same thing was happening as before, nothing opened and nothing showing running in task manager.
I then deleted the app then reinstalled it. The app launched and worked for the FS2020 flight. I completed my flight and exited Fs2020 and closed fs2ff and shut down the computer. Upon computer startup, loaded the app, nothing happened.
I was able to delete and reinstall the app a few times to get it to work but now when I delete and reinstall, nothing happens

**Comment by astenlund** [comment] 2020-10-18 22:15
Closing as duplicate of #11 (original issue re-opened).

**Closed by astenlund** 2020-10-18 22:15 UTC
Labels: bug, duplicate
