### ISSUE TITLE
Does not load

### ISSUE THREAD

**Issue by pdxpilot** [astenlund/fs2ff#11] opened 2020-10-14 20:40 UTC
Hey Andreas,
I have downloaded this version and when I launch the app, I get the windows firewall message and i select to allow and then nothing happens. I try launching the app again and nothing opens up. I don’t see it running in task manager. I have the latest version of Windows 10 all up to date. i9 9900k, 32gb memory, NVIDIA 2070 super, custom built just for fs2020.
Any Ideas?

**Comment by astenlund** [comment] 2020-10-14 23:10
Hmm, interesting... Could you have a look in the Event Viewer for me? Go to Windows Logs -> Application and search for "fs2ff". Any crash logs should end up there. Thanks!

/Andreas

**Comment by pdxpilot** [comment] 2020-10-14 23:27
Here are a few things I found.
- <#> <Event xmlns="*http://schemas.microsoft.com/win/2004/08/events/event
<http://schemas.microsoft.com/win/2004/08/events/event>*">
- <#> <System>
  <Provider Name="*Application Error*" />
  <EventID Qualifiers="*0*">1000</EventID>
  <Version>0</Version>
  <Level>2</Level>
  <Task>100</Task>
  <Opcode>0</Opcode>
  <Keywords>0x80000000000000</Keywords>
  <TimeCreated SystemTime="*2020-10-14T20:24:35.8819965Z*" />
  <EventRecordID>3975</EventRecordID>
  <Correlation />
  <Execution ProcessID="*0*" ThreadID="*0*" />
  <Channel>Application</Channel>
  <Computer>DESKTOP-238JPKM</Computer>
  <Security />
  </System>
- <#> <EventData>
  <Data>fs2ff.exe</Data>
  <Data>0.1.8.0</Data>
  <Data>5f3ed523</Data>
  <Data>KERNELBASE.dll</Data>
  <Data>10.0.19041.488</Data>
  <Data>5b4a3325</Data>
  <Data>e0434352</Data>
  <Data>0000000000023e49</Data>
  <Data>2da8</Data>
  <Data>01d6a2680837f7c2</Data>
  <Data>D:\Downloads\fs2ff.exe</Data>
  <Data>C:\Windows\System32\KERNELBASE.dll</Data>
  <Data>e7838476-a3a6-4122-b004-10f87f2fc98e</Data>
  <Data />
  <Data />
  </EventData>
  </Event>

- <#> <Event xmlns="*http://schemas.microsoft.com/win/2004/08/events/event
<http://schemas.microsoft.com/win/2004/08/events/event>*">
- <#> <System>
  <Provider Name="*.NET Runtime*" />
  <EventID Qualifiers="*0*">1026</EventID>
  <Version>0</Version>
  <Level>2</Level>
  <Task>0</Task>
  <Opcode>0</Opcode>
  <Keywords>0x80000000000000</Keywords>
  <TimeCreated SystemTime="*2020-10-14T20:26:27.6683533Z*" />
  <EventRecordID>3982</EventRecordID>
  <Correlation />
  <Execution ProcessID="*0*" ThreadID="*0*" />
  <Channel>Application</Channel>
  <Computer>DESKTOP-238JPKM</Computer>
  <Security />
  </System>
- <#> <EventData>
  <Data>Application: fs2ff.exe CoreCLR Version: 4.700.20.41105 .NET Core
Version: 3.1.8 Description: The process was terminated due to an unhandled
exception. Exception Info: System.NullReferenceException: Object reference
not set to an instance of an object. at
fs2ff.MainWindow.OnSourceInitialized(EventArgs e) at
System.Windows.Window.CreateSourceWindow(Boolean duringShow) at
System.Windows.Window.CreateSourceWindowDuringShow() at
System.Windows.Window.SafeCreateWindowDuringShow() at
System.Windows.Window.ShowHelper(Object booleanBox) at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate
callback, Object args, Int32 numArgs) at
System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,
Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) at
System.Windows.Threading.DispatcherOperation.InvokeImpl() at
System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object
state) at
MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext
executionContext, ContextCallback callback, Object state) --- End of stack
trace from previous location where exception was thrown --- at
System.Threading.ExecutionContext.RunInternal(ExecutionContext
executionContext, ContextCallback callback, Object state) at
System.Threading.ExecutionContext.Run(ExecutionContext executionContext,
ContextCallback callback, Object state) at
MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext
executionContext, ContextCallback callback, Object state) at
System.Windows.Threading.DispatcherOperation.Invoke() at
System.Windows.Threading.Dispatcher.ProcessQueue() at
System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg,
IntPtr wParam, IntPtr lParam, Boolean& handled) at
MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr
lParam, Boolean& handled) at
MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) at
System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate
callback, Object args, Int32 numArgs) at
System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,
Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) at
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority
priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) at
MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr
wParam, IntPtr lParam) at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&
msg) at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame
frame) at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame
frame) at System.Windows.Threading.Dispatcher.Run() at
System.Windows.Application.RunDispatcher(Object ignore) at
System.Windows.Application.RunInternal(Window window) at
System.Windows.Application.Run() at fs2ff.App.Main()</Data>
  </EventData>
  </Event>

**Comment by astenlund** [comment] 2020-10-14 23:36
Perfect, thank you! Will have a look.

**Comment by pdxpilot** [comment] 2020-10-14 23:47
I did have this work once(one time)with a previous version. The app opened but I was never able to get connected to ForeFlight even directly entering IP address. I then deleted it and installed your latest version hoping it would work.

**Comment by pdxpilot** [comment] 2020-10-18 00:43
I wanted to let you know that I was able to get fs2ff working. Apparently I had my network improperly set. I deleted and reinstalled your app and it’s works perfectly. Thanks for your time. 

Rick

**Comment by astenlund** [comment] 2020-10-18 17:10
OK, cool. The app shouldn't crash but I'm glad you got it working.

Since I can't reproduce the problem, finding the cause is proving a little difficult. Closing, but please feel free to reopen or create a new issue if it happens alot in The Future™.

**Comment by pdxpilot** [comment] 2020-10-18 21:15
So it worked yesterday as I thought it was a network issue and I
uninstalled and reinstalled fs2ff. Today I attempted to launch fs2ff and
the same thing was happening as before, nothing opened and nothing showing
running in task manager.
I then deleted the app then reinstalled it. The app launched and worked for
the FS2020 flight. I completed my flight and exited Fs2020 and closed fs2ff
and shut down the computer. Upon computer startup, loaded the app, nothing
happened.
I was able to delete and reinstall the app a few times to get it to work
but now when I delete and reinstall, nothing happens. I'll submit a trouble
ticket.
Here is what I am finding in the logs.
0



APPCRASH



Not available



0



fs2ff.exe



0.1.8.0



5f3ed523



KERNELBASE.dll



10.0.19041.488



5b4a3325



e0434352



0000000000023e49















\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_fs2ff.exe_4f46244b59225d781cc6a6036d6fcbdc3873bde_fa700d49_191dbc5a-7200-40dc-a917-a7ee8cd1710c







0



bb2b04a0-f320-4049-b98b-845b12ffab30



4







0
*+* *System*


*-* *Provider*



[ *Name*] Windows Error Reporting


*-* *EventID* 1001



[ *Qualifiers*] 0



*Version* 0



*Level* 4



*Task* 0



*Opcode* 0



*Keywords* 0x80000000000000


*-* *TimeCreated*



[ *SystemTime*] 2020-10-18T20:24:00.5178223Z



*EventRecordID* 4511



*Correlation*


*-* *Execution*



[ *ProcessID*] 0



[ *ThreadID*] 0



*Channel* Application



*Computer* DESKTOP-238JPKM



*Security*
*-* *EventData*



1980224748882122988



4



APPCRASH



Not available



0



fs2ff.exe



0.1.8.0



5f3ed523



KERNELBASE.dll



10.0.19041.488



5b4a3325



e0434352



0000000000023e49











\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1EC1.tmp.WERInternalMetadata.xml



\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_fs2ff.exe_4f46244b59225d781cc6a6036d6fcbdc3873bde_fa700d49_191dbc5a-7200-40dc-a917-a7ee8cd1710c







0



bb2b04a0-f320-4049-b98b-845b12ffab30



268435456



c96c7501bef21753cb7b2beadc8e58ec



0
*+* *System*


*-* *Provider*



[ *Name*] Windows Error Reporting


*-* *EventID* 1001



[ *Qualifiers*] 0



*Version* 0



*Level* 4



*Task* 0



*Opcode* 0



*Keywords* 0x80000000000000


*-* *TimeCreated*



[ *SystemTime*] 2020-10-18T21:02:32.3120508Z



*EventRecordID* 4537



*Correlation*


*-* *Execution*



[ *ProcessID*] 0



[ *ThreadID*] 0



*Channel* Application



*Computer* DESKTOP-238JPKM



*Security*
*-* *EventData*



1980224748882122988



4



APPCRASH



Not available



0



fs2ff.exe



0.1.8.0



5f3ed523



KERNELBASE.dll



10.0.19041.488



5b4a3325



e0434352



0000000000023e49











\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6527.tmp.WERInternalMetadata.xml



\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_fs2ff.exe_4f46244b59225d781cc6a6036d6fcbdc3873bde_fa700d49_bb56277e-f7f6-422f-a8c3-b3f1ad92a385







0



ee7ecf3d-f27d-42f3-83fc-7ea82f74aa11



268435456



c96c7501bef21753cb7b2beadc8e58ec



0

**Comment by astenlund** [comment] 2020-10-20 18:07
I've been unable to reproduce the problem, but I pushed a new version that I hope solves it. Available here: https://github.com/astenlund/fs2ff/releases/latest

Please let me know if this works for you, thanks!

**Comment by pdxpilot** [comment] 2020-10-21 20:04
Hi Andreas,

Thank you for looking into this for me.I found out on my end that I was
missing a, vcruntime140.dll, while attempting to open a different program.
I went to  Microsoft Visual C++-2015 Redistributable Page and downloaded
what was missing.
After downloading the .dll, your original app worked just fine. I did
update the app to the latest release and that works as well .

Thank you again.

Rick

**Comment by astenlund** [comment] 2020-10-21 20:51
Great, thanks for the update! I'm not sure if the dll is still needed for my app, but I'm glad you managed to solve it anyway.

**Closed by astenlund** 2020-10-21 20:51 UTC
Labels: bug

**Comment by pdxpilot** [comment] 2020-11-01 16:51
Hi Andreas,
I just wanted to let you know that fs2ff isn’t working for me on the version 5 update. Your app opens and shows connected but nothing shows under devices on ForeFlight. 

I’ll play around with other settings to see if there is something missing on my end. 

Eric

**Comment by pdxpilot** [comment] 2020-11-03 17:55
Hi Andreas,
I got it working again. Apparently windows did an update at the same time FS 5 updated. Windows for some reason changes my WiFi connection from private to public and doesn’t let windows connect to other devices via WiFi. So the take away here if anyone else has this problem is to verify that their WiFi is set to private or home, not public. 

Thanks again. 

Eric

**Comment by astenlund** [comment] 2020-11-03 23:15
Roger, good find.
